from pimsclient.exceptions import PIMSError


class AuthError(PIMSError):
    pass
